Thoracic Site Setup
parameter1/ascend-media-websites pull request #350
Opened 2022-08-08 19:41 UTC by Shinsina

![Initial-Setup](https://user-images.githubusercontent.com/46794001/183500795-bb204b56-9f76-41f5-817a-a027ecad3454.png)

2022-08-08 19:41 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [New site: Thoracic](https://trello.com/c/kDnDdp3n/325-new-site-thoracic)

2022-08-09 19:17 UTC, solocommand requested changes

2022-08-09 19:17 UTC, solocommand commented on docker-compose.yml
> +    ports:
All BaseCMS website service definitions should now use the `hostname` service key, and include the `HOST` environment variable, to ensure a consistently unique cookie domain across environments. This ensure both that the IdentityX, Omeda, and P1Events contexts (where applicable) will be correct when switching between sites.

```suggestion
      SITE_ID: 62f156eeb42f9308288b45e8
      HOST: www-ascend-thoracic.dev.parameter1.com
    hostname: www-ascend-thoracic.dev.parameter1.com
    ports:
```

2022-08-09 19:17 UTC, solocommand commented on .github/workflows/deploy-staging.yml
> +          - thoracicam.com
May as well add to the production deploy so it doesn't get forgotten, even if the container infrastructure/routing hasn't been stood up yet.

2022-08-10 19:18 UTC, solocommand approved these changes

2022-08-10 20:37 UTC, closed without merging

2022-08-10 20:38 UTC, brandonbk commented
@Shinsina - closing this for now...it wasn't communicated that this site will not use the same theme as previous sites.  We can reopen and/or steal the appropriate pieces after next week's meeting.