Alter Native-X Story Template to look more like the Native-X implementation.
parameter1/ascend-media-websites pull request #383
Opened 2022-09-27 20:05 UTC by Shinsina

![Testing-Native-X](https://user-images.githubusercontent.com/46794001/192624616-d55ee26d-380a-4106-a8e4-4e042dac48ae.png)

2022-09-27 20:06 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [NativeX Integrated Stories - Full Width Image](https://trello.com/c/zW4j6Nti/354-nativex-integrated-stories-full-width-image)

2022-10-04 14:21 UTC, B77Mills requested changes

2022-10-04 14:21 UTC, B77Mills commented on packages/global/components/document.marko
> +$ if (req.path.match(/sponsored/)) {
@Shinsina  This would no longer be needed if we added the component mentioned in the below comment.

2022-10-04 14:21 UTC, B77Mills commented on packages/global/templates/content/native-x-story.marko
>  <marko-web-default-page-layout type="native-x-story">
@Shinsina  Instead of making the req.path.match check in the document.marko we should ad a new `page/native-x.marko` component that gets called here so instead of calling `<marko-web-default-page-layout>`

Call something like <global-native-x-page type="native-x-story">

The component should look something like 
```
$ const {
  type = "default",
  title,
  description,
  head,
  page,
  abovePage,
  belowPage,
  ...rest
} = input;
$ const { document } = out.global;

<${document} ...rest>
  <@head>
    <marko-web-default-page-metadata title=title description=description />
    <${head} />
  </@head>
  <!-- Note: camelcased vars due to nest input of dynamic document. perhaps a marko bug -->
  <@container abovePage=abovePage belowPage=belowPage modifiers=["native-x-story"]>
    <@page for=type>
      <${page} />
    </@page>
  </@container>
</>
```

2022-10-04 15:04 UTC, B77Mills commented on packages/daily/templates/content/native-x-story.marko
>  $ const { id, type } = content;
@Shinsina Can we get title & description(teaser) so we can pass title & description in to the `<global-daily-native-x-story-page>` component so it can correctly set the metadata info in the new component.

2022-10-04 15:38 UTC, B77Mills approved these changes

2022-10-04 15:56 UTC, merged