Update Load More, enable reskin AD for AAD Company Pages
parameter1/ascend-media-websites pull request #385
Opened 2022-09-30 15:30 UTC by Shinsina

AAD Press Release Behavior:
![AAD-PRESS-RELEASE-1](https://user-images.githubusercontent.com/46794001/193304488-804735ed-1596-4cd4-8798-2b9457ea1ad5.png)
![AAD-Press-Release](https://user-images.githubusercontent.com/46794001/193304549-3cf5eef0-d443-4451-9ab5-bc924dc75e30.png)

AAD Article Behavior:
![AAD-Article](https://user-images.githubusercontent.com/46794001/193304618-94ebf126-1b45-4a66-a359-455316fbe8fb.png)

AUA Press Release Behavior (To show restriction logic isn't applied elsewhere):
![Press-Release-AUA](https://user-images.githubusercontent.com/46794001/193304736-c93b416e-afac-42f0-9dc8-b169e60afb0d.png)

NOTE: At time of PR I have no added the Reskin ad unit to the AAD GAM configuration on the GAM side.

2022-09-30 15:30 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [AAD Content types and GAM ad unit for reskin](https://trello.com/c/OOBHMxJL/359-aad-content-types-and-gam-ad-unit-for-reskin)

2022-10-03 13:57 UTC, brandonbk requested changes

2022-10-03 13:57 UTC, brandonbk commented on packages/global/templates/content/index.marko
> +        $ const aadRules = ["AAD"].includes(site.get("siteAcronym")) && ['press-release'].includes(type);
Generally speaking, specific site names shouldn't be used within shared templates for conditional logic.  Instead, these values should be agnostic/generic, such as "loadMoreHeader" and "loadMoreContentTypes".  Or alternatively, the global content template should be converted into a layout component, so that each site can have its own content template for passing in various values.

2022-10-04 15:52 UTC, B77Mills requested changes

2022-10-04 15:52 UTC, B77Mills commented on packages/global/templates/content/index.marko
> +        $ const noLoadMore = contentPageLoadMoreSettings && getAsArray(contentPageLoadMoreSettings, 'restrictedOn').includes(type);
@Shinsina  can we change this to enableLoadMore = contentPageLoadMoreSettings && !getAsArray(contentPageLoadMoreSettings, 'restrictedOn').includes(type);

2022-10-04 15:52 UTC, B77Mills commented on packages/global/templates/content/index.marko
> +        <if(!noLoadMore)>
@Shinsina  update this to <if(enableLoadMore)>

2022-10-04 16:47 UTC, B77Mills approved these changes

2022-10-04 16:47 UTC, merged