Add nativeX route for ‘Industry Highlights’ section
parameter1/ascend-media-websites pull request #429
Opened 2022-12-01 18:01 UTC by jwade1327

<img width="1335" alt="Screen Shot 2022-12-01 at 11 50 30 AM" src="https://user-images.githubusercontent.com/64623209/205126763-f3a79056-e764-4826-a94e-c74ddd1bc0db.png">
<img width="1415" alt="Screen Shot 2022-12-01 at 11 56 56 AM" src="https://user-images.githubusercontent.com/64623209/205126774-c6c16065-294d-432c-b4d6-fbdd4591e93d.png">
<img width="1102" alt="Screen Shot 2022-12-01 at 11 57 20 AM" src="https://user-images.githubusercontent.com/64623209/205126777-40213828-80f5-42ed-8415-416b35797927.png">

2022-12-01 18:01 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add NativeX Ads to Industry Highlights Channels for the following sites (like we did for Sessions): https://www.aadmeetingnews.org https://isc.hub.heart.org https://www.auadailynews.org/](https://trello.com/c/Qkt8NgUo/404-add-nativex-ads-to-industry-highlights-channels-for-the-following-sites-like-we-did-for-sessions-https-wwwaadmeetingnewsorg-http)

2022-12-01 18:15 UTC, Shinsina requested changes
Ref: https://github.com/parameter1/ascend-media-websites/pull/381 These need to have an `industry-highlights` Native-X channel created in order for this to "work as intended"

2022-12-01 19:14 UTC, Shinsina commented on sites/auadailynews.org/config/site.js
> +  nativeXHeroSections: ['industry-highlights'],
I don't believe this needs to exist anywhere anymore, this was likely forgotten about when we switch it from just the hero block pulling Native-X ads to the entire section page template. Can you confirm?

2022-12-01 19:29 UTC, jwade1327 commented on sites/auadailynews.org/config/site.js
> +  nativeXHeroSections: ['industry-highlights'],
@Shinsina Can confirm this is not needed (I also removed it from sessions site config)

2022-12-02 13:28 UTC, Shinsina approved these changes

2022-12-02 13:29 UTC, merged

2023-01-13 16:34 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Industry Highlights section change to all Native](https://trello.com/c/7wNagrTL/415-industry-highlights-section-change-to-all-native)