Show ‘About the Bulletin’
parameter1/ascend-media-websites pull request #452
Opened 2023-02-01 17:14 UTC by jwade1327

<img width="1349" alt="Screen Shot 2023-02-01 at 11 13 35 AM" src="https://user-images.githubusercontent.com/64623209/216114016-f1273d0a-444c-43ac-8752-496957ad4554.png">

2023-02-01 17:14 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AAO-HNS Bulletin About US](https://trello.com/c/AJCD5Twb/428-aao-hns-bulletin-about-us)

2023-02-01 19:29 UTC, B77Mills approved these changes

2023-02-01 20:35 UTC, Shinsina requested changes

2023-02-01 20:35 UTC, Shinsina commented on sites/bulletin.entnet.org/config/navigation.js
> +  { href: '/about-the-bulletin', label: 'About The Bulletin' },
![Screenshot from 2023-02-01 14-35-58](https://user-images.githubusercontent.com/46794001/216157431-e00cb2c9-46f9-4ce3-a58d-2fb5065d6a8e.png)

This doesn't go anywhere currently.

2023-02-02 13:00 UTC, jwade1327 commented on sites/bulletin.entnet.org/config/navigation.js
> +  { href: '/about-the-bulletin', label: 'About The Bulletin' },
@Shinsina It is a section in Base (just updated)

2023-02-02 15:46 UTC, Shinsina requested changes
There isn't routing currently for this site that supports `/about-the-bulletin` going anywhere hence even with it being  a section in Base, the site doesn't know/care about it. The routing (and potentially the associated template) will need to added and/or created in order for this to do anything.

2023-02-03 20:13 UTC, Shinsina requested changes

2023-02-03 20:13 UTC, Shinsina commented on sites/bulletin.entnet.org/server/graphql/fragments/content-page.js
> +const gql = require('graphql-tag');
Are all these fields being returned actually being used? I would take a look at `packages/daily-templates/website-section/index.marko` specifically the `queryFragment` it's using and see if that works here, then we aren't having to query for a bunch of unused fields and further we are using a fragment whose name is more reflective as to how it is being used `content-page` reads to me like it would be used on a content page and not a section page like it is here

2023-02-06 14:00 UTC, Shinsina approved these changes

2023-02-06 14:00 UTC, merged