If content type ‘page’ don’t display right rail
parameter1/ascend-media-websites pull request #469
Opened 2023-05-02 20:03 UTC by jwade1327

<img width="1439" alt="Screen Shot 2023-05-02 at 3 01 44 PM" src="https://user-images.githubusercontent.com/64623209/235773343-a36e8a00-5114-461f-9510-1687abf58484.png">

2023-05-02 20:03 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [amPulmonary Site Punch List](https://trello.com/c/91mbqY5r/420-ampulmonary-site-punch-list)

2023-05-02 20:15 UTC, Shinsina requested changes
@jwade1327 This should then use something more akin to this: https://github.com/parameter1/ascend-media-websites/blob/master/packages/global-monorail/templates/content/contact-us.marko

Likely course of action would be to replace https://github.com/parameter1/ascend-media-websites/blob/master/packages/global-monorail/templates/dynamic-page/index.marko with something akin to the above. This is how https://www.ampulmonary.com/page/contact-us is setup albeit with the contact us form in "the rail".

This looks weird right now since there isn't any content primary to "Home" (which is great but this is trying to pull "More In Home" (which is empty) and then loads the most popular block alongside it (hence the rail still loads here)

2023-05-04 16:42 UTC, Shinsina requested changes

2023-05-04 16:42 UTC, Shinsina commented on packages/global-monorail/components/layouts/content/wrapper.marko
> +  <if(type!== "page")>
Check the spacing on this

2023-05-05 13:44 UTC, Shinsina approved these changes

2023-05-05 13:48 UTC, merged