Add About Us to navigation and footer
parameter1/ascend-media-websites pull request #478
Opened 2023-05-23 18:30 UTC by jwade1327

<img width="1277" alt="Screen Shot 2023-05-23 at 1 29 20 PM" src="https://github.com/parameter1/ascend-media-websites/assets/64623209/466f2754-400f-4e5b-9730-eb546fea72e0">
<img width="994" alt="Screen Shot 2023-05-23 at 1 30 41 PM" src="https://github.com/parameter1/ascend-media-websites/assets/64623209/834ca1a4-a518-4587-aadd-63cbdbb56504">

2023-05-23 18:31 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [amPulmonary - Add About Us to the website](https://trello.com/c/ISHyHbQX/470-ampulmonary-add-about-us-to-the-website)

2023-05-23 18:41 UTC, Shinsina requested changes

2023-05-23 18:41 UTC, Shinsina commented on sites/ampulmonary.com/config/navigation.js
> +];
Confused as to why this was renamed to utilities when it's only being used under the portion of the menu labeled `Resources` is this intended?

2023-05-24 18:21 UTC, Shinsina approved these changes

2023-05-24 18:28 UTC, merged