newsletter signup styling adjustments
parameter1/ascend-media-websites pull request #496
Opened 2023-07-17 19:26 UTC by jwade1327

<img width="1192" alt="Screen Shot 2023-07-17 at 2 24 49 PM" src="https://github.com/parameter1/ascend-media-websites/assets/64623209/46e623fe-a416-4306-b81f-bf965160c3e1">
<img width="1275" alt="Screen Shot 2023-07-17 at 2 25 12 PM" src="https://github.com/parameter1/ascend-media-websites/assets/64623209/cb0e27be-abd8-4d92-933e-f3bf4ec820fd">

2023-07-17 19:27 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add Newsletter Sign up block for amPulmonary](https://trello.com/c/5riHjl89/455-add-newsletter-sign-up-block-for-ampulmonary)

2023-07-17 19:37 UTC, Shinsina requested changes
This is coming from `.newsletter-signup-banner--large {
  flex-direction: row;
}`

Not sure what the intent is in setting this in the first place but it is breaking this:

![Screenshot from 2023-07-17 14-37-05](https://github.com/parameter1/ascend-media-websites/assets/46794001/df8e9a5e-73ed-411b-aa99-96a173cf61c8)

2023-07-18 12:12 UTC, jwade1327 commented
@Shinsina I was looking at the inline content piece. I removed the image and now, each block is displaying as intended

2023-07-18 13:17 UTC, Shinsina requested changes

2023-07-18 13:32 UTC, merged