Make bulletin site
parameter1/ascend-media-websites pull request #86
Opened 2021-01-15 17:21 UTC by B77Mills

Initial Setup of new bulletin theme and site for https://bulletin.entnet.org/

2021-01-15 19:15 UTC, solocommand commented
@B77Mills I changed this back to tauron/ascend, added the site/section/option and magazine/issue/section to the database. Created the first piece of content and scheduled appropriately.

After updating the configs, this is now available https://bulletin-entnet-org.www.base.parameter1.com and will deploy there automatically when versioned.

A couple things to resolve:
- The text in the header image is misspelled ("oicial")
- I don't know what this site is supposed to look like design-wise, but it is possible to query by magazine section to make the issue/homepage look like their current site.
- The site footer seems to be missing entirely
- This is not a reusable site/template, there should be no `packages/bulletin`. Put your templates, layouts, and components under the site folder.
- The header should not be one giant image, as it cuts off the menu when approaching a tablet resolution. At the very least, this needs to be two images so that the description text can be removed when scaling down.
- Your magazine archive query needs to be updated to include the cover image
- Social icons/links are to the American Heart Association.

![screencapture-bulletin-entnet-org-www-base-parameter1-2021-01-15-13_14_37](https://user-images.githubusercontent.com/1778222/104768686-ac43b880-5733-11eb-86f1-61a884fd19ea.png)

2021-01-21 02:56 UTC, B77Mills commented
@solocommand I have not migrated the package to the site folder, but I believe the other issue have been addressed.  Can we review in the am and try to get them a beta site to look at.

2021-01-21 17:21 UTC, solocommand requested changes

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/browser/jump-modal.vue
> +<template>
Remove or update to be specific to the AAO site/logo

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/browser/index.js
> +import jQuery from '@base-cms/marko-web/browser/jquery-full';
Remove jQuery, not used.

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/early-career.marko
> +import queryFragment from "../../graphql/fragments/vascular-early-career";
Remove if not used, this was for the vascular hub. If this is being used, it needs its own fragment

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/eposters-mr.marko
> +import { buildImgixUrl } from "@base-cms/image";
Unused

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/exhibitors-banner.marko
> +import { buildImgixUrl } from "@base-cms/image";
Likely not used, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/event-schedule.marko
> +import { getAsObject, get } from "@base-cms/object-path";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/exhibits-mr.marko
> +import { buildImgixUrl } from "@base-cms/image";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/featured-exhibitors-full.marko
> +import { getAsObject, get } from "@base-cms/object-path";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/featured-exhibitors.marko
> +import { getAsObject, get } from "@base-cms/object-path";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/follow-us.marko
> +import { asObject } from "@base-cms/utils";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/global-right-rail.marko
> +$ const { GAM } = out.global;
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/qcor-chat-button.marko
> +import { buildImgixUrl } from "@base-cms/image";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/qcor-early-career-plenary-buttons.marko
> +import { buildImgixUrl } from "@base-cms/image";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/science-news.marko
> +import { getAsObject, get, getAsArray } from "@base-cms/object-path";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/blocks/watch-listen.marko
> +import { getAsObject, get, getAsArray } from "@base-cms/object-path";
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/components/elements/early-career-blogs-button.marko
> +<marko-web-link
Unused, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/fragments.js
> +  bullitenContentList,
Typo; `bulletinContentList`, etc

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/announcements.js
> +const gql = require('graphql-tag');
Are announcements being used on this site? delete if not

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/event-schedule.js
> +const gql = require('graphql-tag');
Likely unused

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/featured-exhibitors-full.js
> +const gql = require('graphql-tag');
likely unused

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/featured-exhibitors.js
> +const gql = require('graphql-tag');
likely unused

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/message.js
> +const gql = require('graphql-tag');
Specific to hub stuff again, remove if not actually used.

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/science-news.js
> +const gql = require('graphql-tag');
hub, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/vascular-early-career.js
> +const gql = require('graphql-tag');
vascular hub, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/graphql/fragments/watch-listen.js
> +const gql = require('graphql-tag');
hub block, remove

2021-01-21 17:21 UTC, solocommand commented on packages/bulletin/native-x/build-config.js
> +const NativeXConfiguration = require('@base-cms/marko-web-native-x/config');
The bulletin package should be included _in addition to_ the existing `shared` package. You should always load these files from shared to prevent unnecessary duplication unless you need to make changes to them.

2021-01-21 19:41 UTC, solocommand requested changes
@B77Mills Looks good. A couple more files to remove from the site and this should be good to release.

2021-01-21 19:41 UTC, solocommand commented on sites/bulletin.entnet.org/server/components/blocks/global-right-rail.marko
> +
Unused AHA block, remove

2021-01-21 19:41 UTC, solocommand commented on sites/bulletin.entnet.org/server/components/blocks/marko.json
> +{
Unused, remove

2021-01-21 19:41 UTC, solocommand commented on sites/bulletin.entnet.org/server/components/marko.json
> +{
Unused, remove

2021-01-21 19:41 UTC, solocommand commented on sites/bulletin.entnet.org/server/public/robots.txt
> +Sitemap: https://isc.hub.heart.org/sitemap.xml
I know we're not sure about the domain, but for now make this `https://bulletin.entnet.org` for consistency.

2021-01-21 19:41 UTC, solocommand commented on sites/bulletin.entnet.org/server/utils/shuffle-array.js
> +module.exports = (a) => {
Unused, remove

2021-01-21 20:03 UTC, merged